development:
  adapter: postgresql
  encoding: unicode
  database: studitemps_dev
  username: pr0d1r2
  password: testowanie

test:
  adapter: postgresql
  encoding: unicode
  database: studitemps_test
  username: pr0d1r2
  password: testowanie

production:
  adapter: postgresql
  encoding: unicode
  database: studitemps_prod
  username: pr0d1r2
  password: testowanie
